spring:
  application:
    name: spring-boot-hello

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  data:
    redis:
      host: localhost
      port: 6379